# https://github.com/firebase/firebase-tools
# https://github.com/FirebaseExtended/action-hosting-deploy

name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Checkout source
        uses: actions/checkout@v4

      - name: Build GWT
        run: ./gradlew gwtCompileForDeploy

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_HORZCV }}
          channelId: live
          projectId: horzcv
